- README.md
I also drop TEENY part from 2.1 and 2.2 since this ruby versions follow semver
> Add ruby 2.2 to readme

- .gitignore
Since I made a mistake and committed oj.so in my last pull request, it seems like it should be added to .gitignore as well as cleaned up after the build_test script runs.
> cleanup generated oj.so in build_test script, add to .gitignore

- ext/oj/extconf.rb
- oj.gemspec
Fix for issue #255 
Build makefile in oj/oj as per example in rubygems: http://guides.rubygems.org/gems-with-extensions/
> Build makefile in oj/oj as per example in rubygems

- ext/oj/dump.c
`RSTRUCT_PTR()` makes the struct WB-unprotected, and causes GC penalty.
> constify RStruct access

- ext/oj/parse.c
- test/test_various.rb
Hi,
I stumbled upon this:
>> Oj.load '[10000000000000000000]'
=> [-8446744073709551616]
And I think I managed to find and fix it (substracting <tt>zero_cnt</tt> seems to only make sense for the decimal part, and <tt>LONG_MAX</tt> check doesn't catch it because one iteration it's below and the next one it's already overflowed).
Couldn't calculating the actual number <tt>ni.i</tt> be removed completely here?
Also, there is the same code part in sparse.c which I did not change. I'm assuming it's for strict parsing? But when playing a bit it seemed that parse.c was also used for strict. So since I didn't know how to test it, I left it alone even though probably it needs the same fix.
PS. Awesome work with the lib, I've had an amazing performance improvement after switching to it some time …
> fix parsing big numbers with trailing zeros

- README.md
I had an issue this morning due to the default nature of the escape encoding, and had to look at C code to find out what I could do about it. This documentation should definitely be top level.
> Adding hard-to-find option documenation to readme

- ext/oj/hash_test.c
Oj's native extension doesn't compile on Solaris and Ruby 2.3.0.
This is because as of r52703, `-D_XOPEN_SOURCE=xxx` may be specified on Solaris.
> the second parameter of gettimeofday() should be NULL

- .travis.yml
Travis workers has two cores. We should use them if possible.
> Compile extension in parallel

- ext/oj/fast.c
- ext/oj/oj.c
Ruby 2.4 will unify Bignum and Fixnum to Integer. ref. https://bugs.ruby-lang.org/issues/12005
I couldn't build oj-2.16.0 on ruby 2.4 with folloing error.
```
compiling ../../../../ext/oj/fast.c
../../../../ext/oj/fast.c:1284:24: error: use of undeclared identifier 'rb_cFixnum'
case T_FIXNUM:  type = rb_cFixnum;      break;
^
1 error generated.
gmake: *** [Makefile:241: fast.o] Error 1
```
I fixed this to use `RUBY_INTEGER_UNIFICATION` provided from Ruby 2.4.
> Support to Integer unification for Ruby 2.4. 

- ext/oj/oj.c
- test/isolated/shared.rb
The JSON module does not use any before separator when pretty generating JSON. This can be shown with this command:
```
$ ruby -rjson -e "puts JSON.pretty_generate(test: true, hello: 'world')"
{
"test": true,
"hello": "world"
}
```
This patch ensures that no `before_sep` is used when calling `pretty_generate`. Although the change is trivial, I think it is important for users who wish to transition to `Oj`. They will not have to deal with breaking any assertions they may have about the output of JSON in their test suites. I noticed this while working on https://github.com/ianks/yagni_json_encoder, which currently passes the entire Rails test suite minus this spec.
> Do not use a before_sep in pretty_generate

- README.md
- ext/oj/oj.c
- ext/oj/oj.h
- ext/oj/parse.c
- test/isolated/shared.rb
- test/test_various.rb
Many JSON parsers (including Ruby's JSON module and Javascripts `JSON.parse`),
raise exceptions when only whitespace is given as an input string. This patch
adds an optional configuration parameter to raise an exception when an empty
string is given as an input.
This change also updates the Mimic configuration to use this by default, which
corresponds to the behavior of `JSON.parse`. This can be illustrated by running:
```
$ ruby -rjson -e "JSON.parse('   ')"
/home/ianks/.gem/ruby/2.3.1/gems/json-2.0.3/lib/json/common.rb:156:in `parse': 743: unexpected token at '' (JSON::ParserError)
from /home/ianks/.gem/ruby/2.3.1/gems/json-2.0.3/lib/json/common.rb:156:in `parse'
from -e:1:in `<main>'
```
Oj now raises a similar exception:
```
$ ruby -roj -e "Oj.mimic_JSON; JSON.parse('   ')"
-e:1:in …
```
> Add option to raise Exception on empty strings

- ext/oj/oj.c
- test/test_writer.rb
```ruby
w = Oj::StringWriter.new
w.push_object()
w.push_value(nil, 'nothing')
```
=> `Can not push onto an Object without a key. (StandardError)`
> Can not push onto an Object without a key

- ext/oj/dump.h
- ext/oj/dump_leaf.c
- ext/oj/string_writer.c
I was not able to `gem install oj` inside of a docker container because of the error:
```
Error relocating /usr/local/bundle/gems/oj-3.0.0/lib/oj/oj.so: dump_cstr: symbol not found - /usr/local/bundle/gems/oj-3.0.0/lib/oj/oj.so
```
After some digging i noticed the functions `dump_cstr` and `obj_dump_comp_val` were externed but not defined anywhere. I guess these were optimized away at link time?
This is just a quick fix and honestly I'm suprised it fixed my problem. Maybe I broke something but the tests seem to work.
> Remove calls to `dump_cstr` and `obj_dump_comp_val`

- ext/oj/rails.c
The `Oj::Rails::mimic_JSON` method is being defined with a trailing question mark. The documentation suggests that this isn't intentional:
https://github.com/ohler55/oj/blob/master/pages/Rails.md
> Fix typo in method name

- .travis.yml
We can not build current version oj gem on ruby 1.9.3.
When we try build it, these error has occurred.
> ruby: symbol lookup error: /path/to/oj.so: undefined symbol: RSTRUCT_GET
`RSTRUCT_GET` macro was introduced on ruby 2.1.0.
ref: https://github.com/ruby/ruby/commit/6a1101f23ea403a8825c2f361508eeb85878b011
So drop ruby 1.9.3 from test targets.
> Drop ruby 1.9.3 from test targets

- test/tests.rb
"test/tests.rb" is a file which runs other test files.
Ordering required test files helps us to detect wihich
files are loaded.
> Order required test files by there name

- test/helper.rb
- test/isolated/shared.rb
- test/json_gem/json_encoding_test.rb
- test/test_file.rb
- test/test_object.rb
- test/test_various.rb
Currently we do not support these ruby versions and do not
run tests against them.
So we do not need to check RUBY_VERSION for ruby 1.8 and 1.9.
> Remove RUBY_VERSION check for ruby 1.8 and 1.9

- oj.gemspec
Add minimum ruby version to gemspec, so it can be reported by rubygems.
> Update oj.gemspec to include a minimum ruby version

- oj.gemspec
rake-compiler v1.0 was released on June 20, 2016.
This commit will allow developers to use rake-compiler v1.0.
> Relax a version constraint on rake-compiler

- oj.gemspec
- remove trailing whitespace
- percent literal not required for simple strings
> Fix description in gemspec

- oj.gemspec
This commit will suppress an open-ended dependency warning
when `gem build oj.gemspec` is executed.
> Suppress an open-ended dependency warning

- ext/oj/extconf.rb
`RSTRUCT_LEN` on Ruby 2.4.0 and 2.4.1 returns an
Integer VALUE. But other versions return `long`.
So we should check patch version of Ruby when
defining `UNIFY_FIXNUM_AND_BIGNUM` macro.
ref:
* Ruby r55788 changed the type of `RSTRUCT_LEN` from
`long` to an Integer VALUE.
https://github.com/ruby/ruby/commit/26f59b09fe3a1c2ec50145f7c3d5b425f48a7a32
* Ruby r58359 fixed these incompatibility issue.
https://github.com/ruby/ruby/commit/8e64799c9614cf18541b04c66a46e0d081d39f57
* Ruby r58636 backported r58359 to 2_4 branch.
https://svn.ruby-lang.org/cgi-bin/viewvc.cgi?view=revision&revision=58636
> Fix tests which are failed on Ruby trunk

- ext/oj/custom.c
- ext/oj/dump_compat.c
- ext/oj/dump_object.c
- ext/oj/extconf.rb
- ext/oj/object.c
- ext/oj/rails.c
We use this macro only to check we should cast returned value of
`RSTRUCT_LEN` to `long`. So `RSTRUCT_LEN_RETURNS_INTEGER_OBJECT`
is better.
By the way, we can use `RUBY_INTEGER_UNIFICATION` macro to detect
Integer is unified or not.
> Rename `UNIFY_FIXNUM_AND_BIGNUM` macro

- ext/oj/extconf.rb
- ext/oj/odd.c
We do not support Ruby 1.8, so we can remove this macro.
> Drop `DATETIME_1_8` macro

- ext/oj/mimic_json.c
If we pass `"11"` to 3rd argument of `rb_scan_args`,
`rb_scan_args` raises `ArgumentError` when `argc` is not
1 nor 2.
This commit changes to raise `ArgumentError` if `argc > 2`.
> Use `rb_scan_args` to check args

- ext/oj/object.c
- test/test_object.rb
Hi
When loading an array into a new `Struct` with `hat_value()`, `oj` checks if there are more items than `Struct` fields and raises an error if that's the case. It doesn't verify if the number of items is lower than the number of fields. The problem is that when this happens, inexistent values are loaded into the fields which leads to corrupt data and unexpected Ruby crashes.
This PR changes this behavior by only setting the fields for which we have a value in the array. Fields that don't have a defined value will remain `nil`. I also added a test for it but I believe it could lead to Ruby crashes under certain circumstances.
---
After having added a new field on an existing struct, we started experiencing Ruby crashes during garbage collection and weird values in the extra-field, making …
>  Fix loading array into struct in hat_value() 

- oj.gemspec
Hi, and thanks for `oj` for all this time.
I looked at the [metadata](http://guides.rubygems.org/specification-reference/#metadata), and added a few links. These would show up in the RubyGems website interface, and also be neat metadata.
> gemspec: add metadata URLs, drop rubyforge_project

- CHANGELOG.md
- ext/oj/custom.c
- ext/oj/design.txt
- ext/oj/mimic_json.c
- ext/oj/object.c
- ext/oj/rails.c
- ext/oj/saj.c
- pages/Encoding.md
- pages/Options.md
- pages/Rails.md
- test/json_gem/README.md
- Update Rails docs to describe TracePoint usage
- Fix some typos
```bash
misspell  -w -error -source=text -i "clas,class" .
```
I'm not sure if the `clas/class` is important. I didn't look too hard.
There's also an interesting false positive matching 'alse' for false, though I don't
know why the 'f' is missing offhand.
```
+++ b/ext/oj/sparse.c
@@ -161,7 +161,7 @@ read_true(ParseInfo pi) {
static void
read_false(ParseInfo pi) {
-    if (0 == reader_expect(&pi->rd, "alse")) {
+    if (0 == reader_expect(&pi->rd, "else")) {
```
> Doc cleanup

- CHANGELOG.md
Thanks to create this gem!
I found typo when I read this CHANGELOG.
I fixed typo on CHANGELOG.md.
> Fix typo on CHANGELOG

- lib/oj/mimic.rb
This PR fixes a YARD comment warning:
```
lib/oj/mimic.rb:34: [UnknownParam] @param tag has unknown parameter name: mimic_path. Did you mean `mimic_paths`?
```
> Update YARD comment to avoid warning

- pages/Security.md
Security documentation was introduced with the `strict_load` method in 189a372c, but the method was renamed to `safe_load` in 11fd80a9 without updating documentation.
> Change `Oj.strict_load` to `Oj.safe_load` in Security docs

- lib/oj/json.rb
This library, as it stands, is removing the top-level `::Parser` constant when the `json.rb` file is required. That breaks the require of other libraries that depend on the `::Parser` constant being available (for example, from https://github.com/whitequark/parser):
```ruby
$ bundle exec pry
[1] pry(main)> require 'parser'
=> true
[2] pry(main)> require 'oj/json'
=> true
[3] pry(main)> require 'rubocop'
NameError: uninitialized constant RuboCop::AST::Parser
Did you mean?  ParseError
from /Users/ufuk/.gem/ruby/2.5.5/gems/rubocop-0.72.0/lib/rubocop/ast/node.rb:21:in `<module:AST>'
```
Instead, the intent here seems to be to just remove the `Parser` constant in the current namespace, which can achieved by doing a simple `remove_const :Parser`.
> Stop removing `::Parser` top-level constant

- ext/oj/rails.c
ActiveSupport configuration usually happens in environment files via app configuration which takes precedence over initializers where `Oj.optimize_rails` supposed to be called. This PR modifies set_encoder method to read initial `escape_html_entities_in_json` value from ActiveSupport
> Read initial escape_html from active_support in rails mode

- ext/oj/rails.c
- gemfiles/rails_5.gemfile
- test/activesupport5/Readme.md
- test/activesupport5/abstract_unit.rb
- test/activesupport5/decoding_test.rb
- test/activesupport5/encoding_test.rb
- test/activesupport5/encoding_test_cases.rb
- test/activesupport5/test_helper.rb
- test/activesupport5/time_zone_test_helpers.rb
This is part of #535. Locally I had a test failure but I hope that this won't be the case on Travis.
Edit: Fixes one test case, but another is failing, which is a new test case that wasn't in 5.0.2 (the previous version of tests).
Here's the bug description in Rails:
https://github.com/rails/rails/issues/26132
And the PR that fixed it:
https://github.com/rails/rails/pull/30953
How would you like to proceed in this case? Is it something that Oj should handle?
> Use Rails 5.2.3 test cases

- .travis.yml
We should be running tests against the latest and greatest ruby patches
for each minor version that this library supports.
> Travis: Use the latest ruby patch versions

- pages/Rails.md
- how to use Oj with Rails 3
- which version of Oj to use with earlier Ruby (pre 2.3.0) versions
> Rails compatibility documentation update

- ext/oj/parse.c
- test/json_gem/json_common_interface_test.rb
Fixes #538.
It seems that double are already enough, and better handled by ruby
internals:
```c
VALUE working() {
long double d = 5.23683071;
return rb_float_new((double)d);
}
VALUE not_working() {
long double d = 5.23683071L;
return rb_float_new((double)d);
}
void Init_main() {
rb_define_global_function("working", working, 0);
rb_define_global_function("not_working", not_working, 0);
}
```
`working` returns the correct value, `not_working` returns a floating
point issued stuff (5.2368307099999996).
Moreover, long double are not widely supported in ruby, for instance in
vsnprintf.c, line 528:
```c
#define	LONGDBL		0x008		/* long double; unimplemented */
```
Or the ffi lib doesn't seem to like it either: https://github.com/ffi/ffi/issues/194
> Use double rather than long double in oj_num_as_value

- ext/oj/oj.c
My IDE (RubyMine) keeps complaining about a missing argument to `Oj.dump` and `Oj.load`. This should fix some or all of the `call-seq` occurrences.
> fix API doc

- .travis.yml
There has been an update on the Ruby releases since March 31.
https://www.ruby-lang.org/en/downloads/releases/
- 2.4.10
- 2.5.8
- 2.6.6
- 2.7.1
> run on latest Ruby runtimes

- ext/oj/parse.c
- ext/oj/sparse.c
- test/test_compat.rb
Greater parity with `JSON.parse` on ruby, where it will ignore `/` in case of an invalid escape character. Such as `\”` (curly double quote) will be parsed to just `”`
> Enabled wider compatibility for .compat_load, better parity with JSON.parse in Ruby

- ext/oj/mimic_json.c
- ext/oj/oj.c
- test/helper.rb
- test/json_gem/test_helper.rb
> Fix object movement bugs

- .travis.yml
- gemfiles/rails_5.gemfile
- gemfiles/rails_6.gemfile
Update Rails versions to skip broken `mimemagic` gem and skip `shared-mime-info` native extension installation.
https://github.com/rails/rails/issues/41750
> Install rails dependency for osx in Travis

- .travis.yml
- Rakefile
- gemfiles/rails_6.1.gemfile
- test/activerecord/result_test.rb
Add support of Rails 6.1 in Travis
Rails 6 deprecated `ActiveRecord::Base#to_hash`.
Rails 6.1 removed `ActiveRecord::Base#to_hash`.
https://github.com/rails/rails/pull/33912
Bundler 2.x deprecated `Bundler.with_clean_env`
https://github.com/rubygems/rubygems/blob/a969c0f16aa56cdb69e2a051f2b093427010e1d9/bundler/UPGRADING.md#helper-deprecations
> Add support Rails 6.1

- ext/oj/dump.c
This patch uses standard C library to copy the string
because copying one byte at a time is slow.
This patch will improve `Oj.dump` performance as following.
–                | before   | after    | result
Oj.dump          | 689.236k | 1.853M   | 2.69x
Oj.dump (compat) | 476.107k | 827.446k | 1.74x
Oj.dump (rails)  | 464.545k | 644.494k | 1.39x
- Apple M1
- Ruby 3.0.2
```
Oj.dump    69.210k i/100ms
Oj.dump (compat)    47.123k i/100ms
Oj.dump (rails)    45.911k i/100ms
Oj.dump    689.236k (± 0.2%) i/s -      3.460M in   5.020801s
Oj.dump (compat)    476.107k (± 0.9%) i/s -      2.403M in   5.048128s …
```
> Improve `Oj.dump` performance

- ext/oj/oj.c
If an exception occurs inside Oj.dump, the heap area has not been released.
The heap area allocated by ALLOC_N must be released.
This patch will fix this problem.
```ruby
require 'oj'
data = {
"foo" => "a" * 1024 * 1024 * 10,
1 => "Invalid hash key with strict mode"
}
1000.times do |i|
begin
Oj.dump(data, mode: :strict)
rescue
end
if i % 100 == 0
rss = Integer(`ps -o rss= -p #{Process.pid}`) / 1024.0
puts "#{i}, #{rss}"
end
end
```
```
$ ruby json.rb
0, 49.4375
100, 1051.0
200, 1674.03125
300, 1773.625
400, 1822.171875
500, 1842.078125
600, 1841.015625
700, 1815.65625
800, 1781.53125
900, 1792.28125
```
1.8 GB of memory was used in my enviroment.
```
$ ruby json.rb
0, 49.40625
100, 49.421875
200, 49.53125
300, 49.59375
400, 49.65625
500, 49.6875
600, 49.71875
700, 49.734375
800, 49.765625 …
```
> Fix memory leak in `Oj.dump` if raise an exception

- ext/oj/mimic_json.c
- ext/oj/oj.c
- ext/oj/oj.h
This patch introduces `oj_hash_has_key()` (same as rb_hash_has_key)
to reduce `rb_funcall()` calling because it has a overhead.
This patch will improve `Oj.dump` performance as following.
Oj.dump          | 1.949M   | 1.966M   | −
Oj.dump (compat) | 850.154k | 1.198M   | 1.41x
Oj.dump (rails)  | 657.383k | 840.051k | 1.28x
- Apple M1
- Ruby 3.0.2
```
Oj.dump   198.379k i/100ms
Oj.dump (compat)    86.466k i/100ms
Oj.dump (rails)    66.760k i/100ms
Oj.dump      1.949M (± 0.3%) i/s -      9.919M in   5.088487s
Oj.dump (compat)    850.154k (± 0.3%) i/s - …
```
> Improve performance of `Oj.dump` with compat/rails mode

- ext/oj/object.c
- ext/oj/strict.c
- ext/oj/wab.c
When use non-frozen string as hash key with rb_hash_aset(), it will duplicate and freeze the string internally.
```c
static int
hash_aset_str(st_data_t *key, st_data_t *val, struct update_arg *arg, int existing)
{
if (!existing && !RB_OBJ_FROZEN(*key)) {
*key = rb_hash_key_str(*key);
}
return hash_aset(key, val, arg, existing);
}
```
Refer: https://github.com/ruby/ruby/blob/bda56a03a625793cb3fd110458c3f7323d73705e/hash.c#L2890-L2897
To avoid duplicate and freeze, this patch will give a frozen string in rb_hash_aset().
FYI)
If you use string as hash key, hash object always might have frozen string as key.
```
irb(main):001:0> hash = { "foo" => 42, bar: 55 }
=> {"foo"=>42, :bar=>55}
irb(main):002:0> hash.keys[0].frozen?
=> true
irb(main):003:0> hash.keys[1].frozen?
=> true
```
This patch …
> Improve `Oj.load` performance

- ext/oj/compat.c
- ext/oj/custom.c
- ext/oj/object.c
- ext/oj/strict.c
Convert from String to Symbol, seems that it has some overhead.
This patch will generate Symbol via `rb_intern3()` and `ID2SYM()`.
The same approach seems to be favored by other gems.
(https://github.com/brianmario/mysql2/blob/ca883e1a359a10f48ac5d0ce649827b424110cd7/ext/mysql2/result.c#L171-L172)
Oj.load          | 339.194k | 387.595k | 1.14x
- Apple M1
- Ruby 3.0.2
```
Oj.load    33.731k i/100ms
Oj.load    339.194k (± 0.9%) i/s -      1.720M in   5.072086s
```
```
Oj.load    39.129k i/100ms
Calculating …
```
> Improve performance of `Oj.load` with symbol_keys mode

- ext/oj/oj.c
It looked up one by one to make sure that the supported options were included in passed options.
This approach of looking up the passed hash each time has an overhead.
This patch will extract key and value from the passed options using `rb_hash_foreach()` and check if they are supported or not.
Oj.load          | 381.671k | 419.917k | 1.10x
Oj.dump          | 507.221k | 578.877k | 1.14x
- Apple M1
- Ruby 3.0.2
```
Oj.load    38.287k i/100ms
Oj.dump    51.076k i/100ms
Oj.load    381.671k (± 0.6%) i/s -      1.914M in   5.015868s
Oj.dump    507.221k (± 0.5%) …
```
> Optimize parging option args

- ext/oj/custom.c
- ext/oj/dump.c
- ext/oj/dump_compat.c
- ext/oj/dump_object.c
- ext/oj/dump_strict.c
- ext/oj/odd.c
- ext/oj/parse.c
- ext/oj/rails.c
- ext/oj/wab.c
`rb_string_value_ptr()` attempts implicit type conversion with `#to_str` method.
```c
char *
rb_string_value_ptr(volatile VALUE *ptr)
{
VALUE str = rb_string_value(ptr);
return RSTRING_PTR(str);
}
```
Refer: https://github.com/ruby/ruby/blob/f81964568f954495ad9a517066bd241f5db22059/string.c#L2319-L2324
However, we have already convert to string using `#to_s` method or check the type.
Therefore, This patch will call `RSTRING_PTR()` directly to reduce overhead.
Oj.load          | 419.273k | 421.858k | -
Oj.dump          | 1.233M   | 1.303M   | 1.06x
- Apple M1
- Ruby 3.0.2
```
Oj.load    42.892k i/100ms …
```
> Use `RSTRING_PTR()` to retrieve C string pointer

- ext/oj/dump.c
- ext/oj/parse.c
To reduce overhead, this patch use `rb_enc_get()` instead.
Oj.dump          | 1.319M   | 1.336M   | -
Oj.dump (compat) | 948.393k | 1.125M   | 1.19x
Oj.dump (rails)  | 815.509k | 943.996k | 1.16x
- macOS 12.0 beta 4
- Apple M1
- Ruby 3.0.2
```
Oj.dump   131.400k i/100ms
Oj.dump (compat)    94.239k i/100ms
Oj.dump (rails)    79.788k i/100ms
Oj.dump      1.319M (± 0.7%) i/s -      6.701M in   5.080504s
Oj.dump (compat)    948.393k (± 0.9%) i/s -      4.806M in   5.068098s
Oj.dump (rails)    815.509k (± 0.8%) i/s -      4.149M in   5.087955s
```
```
Warming up …
```
> Use `rb_enc_get()` to retrieve encoding type

- ext/oj/custom.c
- ext/oj/dump.c
- ext/oj/dump_object.c
- ext/oj/parser.c
- ext/oj/rails.c
- ext/oj/usual.c
When it retrieves String object using `rb_sym_to_s()`, it duplicate the internal String of Symbol.
```c
VALUE
rb_sym_to_s(VALUE sym)
{
return str_new_shared(rb_cString, rb_sym2str(sym));
}
```
Refer: https://github.com/ruby/ruby/blob/6f6a84f2f3e82f9554618f080f9b66ded52884cc/string.c#L11136-L11140
There will be no need to duplicate it, since we haven't changed the retrieved String.
This patch will improve performance where it handles Symbols.
Oj.dump          | 807.090k | 1.173M   | 1.45x
Oj.dump (compat) | 760.372k | 1.080M   | 1.42x
Oj.dump (rails)  | 656.976k | 880.951k | 1.34x
- macOS 12.0 beta 4
- Apple M1
- Ruby 3.0.2
```
Warming up …
```
> Use `rb_sym2str()` to retrieve String object

- ext/oj/cache.c
- ext/oj/debug.c
- ext/oj/parser.c
- ext/oj/saj2.c
- ext/oj/usual.c
- ext/oj/validate.c
Trying to get #689 through.
I was running `gem build ...` and `gem install ...` and fixing all compiler errors regarding C90 compatibility until it worked.
> Make code compatible with C90

- ext/oj/extconf.rb
- ext/oj/object.c
- ext/oj/strict.c
- ext/oj/wab.c
`rb_enc_interned_str()` was added in Ruby 3.0 which returns frozen string object.
It has same effect with `# frozen_string_literal: true` magic comment and
The object will be reused and reduce memory usage if you create a frozen String
with the same C string over and over.
Here is memory usage with sample code.
−               | before   | after
--               | --       | --
Oj.dump          | 33.904k  | 25.904k
- macOS 12.0 beta 4
- Apple M1
- Ruby 3.0.2
```
[CPU]====================
Oj.load     3.855k i/100ms
Oj.load     38.190k (± 0.7%) i/s -    192.750k in   5.047359s
[MEMORY]====================
Oj.load …
```
> Reduce memory usage in `Oj.load` with using Ruby 3.0 feature

- CHANGELOG.md
- ext/oj/fast.c
- test/test_fast.rb
```ruby
Oj::Doc.open('{"foo":1}') do |doc|
doc.fetch('/foo/bar') # used to give `1`, now gives `nil`
doc.exists?('/foo/bar') # used to give `true`, now gives `false`
end
```
Closes #707
> Fix `Oj::Doc` behaviour for inexisting path

- ext/oj/object.c
Remove code for unsupported Ruby versions.
Ref:
https://github.com/ohler55/oj/blob/a15eb1a305c34574199cfa33c3aae0b9fe31791e/oj.gemspec#L23
> Remove the code for Ruby 1.8

- Rakefile
if rails version is 6.1.4.1, `Rails.version =~ /4\.\d/` is evaluated as true.
hence regular expressions must check start character.
> Fix rails version check is weird

- ext/oj/dump_object.c
This patch will use switch statement instead to reduce times of rb_type() calling with if statement.
−               | before  | after    | result
--               | --      | --       | --
Oj.dump          | 1.175M  | 1.191M   | 1.014x
- macOS 12.0
- Apple M1
- Ruby 3.0.2
```
Oj.dump   119.325k i/100ms
Oj.dump      1.175M (± 0.3%) i/s -      5.966M in   5.079028
```
```
Oj.dump   117.261k i/100ms
Oj.dump      1.191M (± 0.5%) i/s -      5.980M in   5.021336s
```
```ruby
require 'benchmark/ips'
require 'oj'
json =<<-EOF
{
"$id": …
```
> Reduce rb_type() calling in `Oj.dump`

- ext/oj/mimic_json.c
This PR will optimize the parsing options in `JSON.parse`.
It looked up one by one to make sure that the supported options were included in passed options.
This approach of looking up the passed hash each time has an overhead.
This PR will apply the same changing as https://github.com/ohler55/oj/pull/683
Oj.dump          | 518.709k | 528.462k | 1.019x
- MacBook Pro (M1 Max, 2021)
- macOS 12.0
- Apple M1 Max
- Ruby 3.0.2
```
JSON.parse    51.973k i/100ms
JSON.parse    518.709k (± 0.3%) i/s -      5.197M in  10.019799s
```
```
JSON.parse    52.534k …
```
> Optimize parsing option args in `JSON.parse`

- ext/oj/custom.c
- ext/oj/dump.c
- ext/oj/dump.h
- ext/oj/dump_object.c
To improve `Oj.dump` performance, this PR make `oj_dump_ignore()` an inline function.
Oj.dump          | 1.190M | 1.216M | 1.022x
- MacBook Pro (M1 Max, 2021)
- macOS 12.0
- Apple M1 Max
- Ruby 3.0.2
```
Oj.dump   119.103k i/100ms
Oj.dump      1.190M (± 0.7%) i/s -     11.910M in  10.009672s
```
```
Oj.dump   121.394k i/100ms
Oj.dump      1.216M (± 0.5%) i/s -     12.261M in  10.086493s
```
```ruby
require 'benchmark/ips'
require 'oj'
json =<<-EOF
{
"$id": "https://example.com/person.schema.json",
"$schema": …
```
> Make `oj_dump_ignore()` an inline function

- ext/oj/custom.c
- ext/oj/dump_compat.c
- ext/oj/dump_object.c
- ext/oj/dump_strict.c
- ext/oj/mimic_json.c
- ext/oj/object.c
- ext/oj/oj.c
- ext/oj/rails.c
- ext/oj/wab.c
`rb_ary_entry()` includes boundary value handling, etc.
```c
static inline VALUE
rb_ary_entry_internal(VALUE ary, long offset)
{
long len = RARRAY_LEN(ary);
const VALUE *ptr = RARRAY_CONST_PTR_TRANSIENT(ary);
if (len == 0) return Qnil;
if (offset < 0) {
offset += len;
if (offset < 0) return Qnil;
}
else if (len <= offset) {
return Qnil;
}
return ptr[offset];
}
```
Oj has simply array handling and it does not need them.
This patch will cut off the these overheads.
Oj.dump          | 1.593M | 1.687M | 1.059x
- MacBook Pro (14 inch, 2021)
- macOS 12.0
- Apple M1 Max
- Ruby 3.0.2
```
Oj.dump   159.458k i/100ms …
```
> Use RARRAY_AREF() instead to improve array accessing

- .github/workflows/CI.yml
- .gitignore
- Rakefile
- test/test_saj.rb
This adds basic CI for Windows, Ruby 2.6 thru head (ucrt)
1. '[CI] - add windows-2022 2.6 - master' - workflow - added a separate job for Windows.  Also, removed the restriction on branches, which allows people to run CI in their forks.  If you do work here in another branch and the merge the branches, this may run CI twice.  I can revert.
2. 'test_saj.rb - fix for windows paths' - simple fix for windows paths
3. '[CI] rakefile & .gitignore' - Rakefile - Make cmd handling cross-platform.  Actions CI does 'odd' things with STDOUT, especially on Windows.  Added changes in rakefile are to display output in correct order.  Added tmp dir to .gitignore.
Happy to change anything...
> Actions - Add Windows CI

- ext/oj/dump.c
Unrolling simple processing loops seems to improve performance when compiled with GCC.
Oj.dump (macOS)  | 1.016M | 1.048M | 1.031x
Oj.dump (Linux)  | 0.984M | 1.143M | 1.162x
- macOS
- macOS 12.1
- Apple M1 Max
- Ruby 3.0.2
- Linux
- Zorin OS 16
- gcc version 9.3.0
- Ruby 3.0.2
```
Oj.dump   101.770k i/100ms
Oj.dump      1.016M (± 0.5%) i/s -     10.177M in  10.012877s
```
```
Oj.dump   104.842k i/100ms
Oj.dump      1.048M (± 0.6%) i/s - …
```
> Unroll the loop of string size calculation

- .github/workflows/CI.yml
Seems that Ruby 3.1 was relased at all platforms.
- https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/
- https://rubyinstaller.org/2021/12/31/rubyinstaller-3.1.0-1-released.html
So, this PR will add Ruby 3.1 into CI.
> Add Ruby 3.1 into CI

- ext/oj/dump.c
- ext/oj/dump_compat.c
- ext/oj/dump_strict.c
This patch uses standard C library to copy the string.
(Ref. https://github.com/ohler55/oj/pull/674)
Oj.dump          | 1.046M | 1.102M | 1.054x
- Zorin OS 16
- gcc version 11.1.0
- Ruby 3.1.0
```
Oj.dump   106.035k i/100ms
Oj.dump      1.046M (± 1.0%) i/s -     15.799M in  15.098842s
```
```
Oj.dump   112.786k i/100ms
Oj.dump      1.102M (± 1.1%) i/s -     16.580M in  15.051956s
```
```ruby
require 'benchmark/ips'
require 'oj'
data = {
float: 3.141592653589793,
fixnum: 2 ** 60
} …
```
> Use memcpy() to dump fixnum/float

- ext/oj/oj.h
Ruby has its own implementation of `ruby_snprintf()`, which is used when `snprintf()` is called.
```c
#define snprintf ruby_snprintf
```
https://github.com/ruby/ruby/blob/cb4e2cb55a59833fc4f1f6db2f3082d1ffcafc80/include/ruby/subst.h#L13
I'm guessing that `ruby_snprintf()` will behave differently from `snprintf()`.
(Ref. https://github.com/ohler55/oj/commit/5e9c70775a9ebdd7262d7c47a70498ad48275c33)
Oj.dump          | 1.459M | 1.894M | 1.298x
- MacBook Pro (14 inch, 2021)
- macOS 12.0
- Apple M1 Max
- Ruby 3.1.0
```
Oj.dump   145.852k i/100ms
Oj.dump      1.459M (± 0.8%) i/s -     22.024M in  15.097734s
```
``` …
```
> Use snprintf() of standard C library

- ext/oj/dump.c
Maybe, the standard C library may use SIMD instructions,
so it is faster than our own code.
Similar:
- https://github.com/ohler55/oj/pull/734
- https://github.com/ohler55/oj/pull/674
Oj.dump (macOS)  | 1.699M | 2.020M | 1.189x
Oj.dump (Linux)  | 1.849M | 2.260M | 1.222x
- macOS
- macOS 12.1
- Apple M1 Max
- Ruby 3.1.0
- Linux
- Zorin OS 16
- gcc version 11.1.0
- Ruby 3.1.0
```
Oj.dump   169.730k i/100ms
Oj.dump      1.699M (± 0.7%) i/s -     25.629M in  15.089624s
```
```
Oj.dump   201.206k …
```
> Use memcpy() to dump true/false/null

- ext/oj/fast.c
- ext/oj/intern.c
- ext/oj/oj.c
- ext/oj/stream_writer.c
- ext/oj/string_writer.c
This is now required to avoid warnings on ruby-head.
See: https://bugs.ruby-lang.org/issues/18007
From ruby-head CI:
```
/home/runner/work/oj/oj/lib/oj/oj.so: warning: undefining the allocator of T_DATA class Oj::Cache
/home/runner/work/oj/oj/test/test_custom.rb:302: warning: undefining the allocator of T_DATA class Oj::StringWriter
/home/runner/work/oj/oj/test/test_custom.rb:205: warning: undefining the allocator of T_DATA class Oj::CStack
/home/runner/work/oj/oj/test/test_fast.rb:317: warning: undefining the allocator of T_DATA class Oj::Doc
/home/runner/work/oj/oj/test/test_writer.rb:248: warning: undefining the allocator of T_DATA class Oj::StreamWriter
/home/runner/work/oj/oj/lib/oj/oj.so: warning: undefining the allocator of T_DATA class Oj::Cache …
```
> Undefine uneeded `T_DATA` allocators

- ext/oj/dump.c
- ext/oj/dump_compat.c
- ext/oj/odd.c
- ext/oj/rails.c
- ext/oj/wab.c
By using NUM2LL() macro, seems that it can convert the value faster than rb_num2ll() directly.
```c
#define RB_NUM2LL  rb_num2ll_inline   /**< @alias{rb_num2ll_inline} */
#define NUM2LL     RB_NUM2LL          /**< @old{RB_NUM2LL} */
static inline LONG_LONG
rb_num2ll_inline(VALUE x)
{
if (RB_FIXNUM_P(x))
return RB_FIX2LONG(x);
else
return rb_num2ll(x);
}
```
https://github.com/ruby/ruby/blob/master/include/ruby/internal/arithmetic/long_long.h
Oj.dump (macOS)  | 7.461k | 7.839k | 1.051x
Oj.dump (Linux)  | 8.391k | 9.140k | 1.089x
- macOS
- macOS 12.1
- Apple M1 Max
- Ruby 3.1.0
- Linux
- Zorin OS 16
- gcc version 11.1.0
- Ruby 3.1.0
``` …
```
> Use NUM2LL() macro instead of rb_num2ll()

- ext/oj/custom.c
- ext/oj/dump_compat.c
- ext/oj/dump_object.c
- ext/oj/dump_strict.c
- ext/oj/rails.c
- ext/oj/wab.c
Oj.dump (macOS)  | 7.461k | 7.707k | 1.033x
Oj.dump (Linux)  | 8.391k | 8.660k | 1.032x
- macOS
- macOS 12.1
- Apple M1 Max
- Ruby 3.1.0
- Linux
- Zorin OS 16
- gcc version 11.1.0
- Ruby 3.1.0
```
Oj.dump   737.000  i/100ms
Oj.dump      7.461k (± 1.1%) i/s -    112.024k in  15.015711s
```
```
Oj.dump   763.000  i/100ms
Oj.dump      7.707k (± 0.5%) i/s -    154.889k in  20.096531s
```
``` …
```
> Move assure_size() outside loop to dump array

- ext/oj/oj.h
Ruby has its own implementation of ruby_nonempty_memcpy(), which is used when memcpy() is called.
```c
static inline void *
ruby_nonempty_memcpy(void *dest, const void *src, size_t n)
{
if (n) {
return memcpy(dest, src, n);
}
else {
return dest;
}
}
RBIMPL_SYMBOL_EXPORT_END()
#undef memcpy
#define memcpy ruby_nonempty_memcpy
```
https://github.com/ruby/ruby/blob/master/include/ruby/internal/memory.h
It has an unnecessary `if` statement and it has some overhead.
Similar: https://github.com/ohler55/oj/pull/735
−               | before | after   | result
--               | --     | --      | --
Oj.dump (macOS)  | 7.839k |  8.000k | 1.021x
Oj.dump (Linux)  | 9.140k | 10.043k | 1.099x
- macOS
- macOS 12.1
- Apple M1 Max
- Ruby 3.1.0
- Linux
- …
> Use memcpy() of standard C library

- ext/oj/dump.c
- ext/oj/oj.c
- ext/oj/oj.h
- ext/oj/parse.c
It can get the rb_encoding object based on its index value.
```c
rb_encoding*
rb_enc_get(VALUE obj)
{
return rb_enc_from_index(rb_enc_get_index(obj));
}
```
Since UTF-8 has been used widely, it is sufficient to know only the index in most cases in this part.
Oj.dump          | 1.026M | 1.119M | 1.091x
- MacBook Pro (14 inch, 2021)
- macOS 12.0
- Apple M1 Max
- Ruby 3.1.0
```
Oj.dump   102.823k i/100ms
Oj.dump      1.026M (± 0.4%) i/s -     10.282M in  10.024252s
```
```
Oj.dump   110.736k i/100ms
Oj.dump …
```
> Use index of encoding whether it need to convert

- ext/oj/intern.c
When marshaling using `Oj.object_dump`, it might cause a SEGV with GC.compact.
This patch will fix a SEGV.
Related to https://github.com/ohler55/oj/issues/745
```ruby
require 'oj'
class Foo
end
def dump_and_load(obj)
json = Oj.dump(obj, :indent => 2, :mode => :object)
Oj.object_load(json);
end
1000.times do |i|
obj = Foo.new()
dump_and_load(obj)
GC.verify_compaction_references(double_heap: true, toward: :empty)
puts "#{Integer(`ps -o rss= -p #{Process.pid}`) / 1024.0} MB" if i % 100 == 0
end
```
> Fix class cache to solve a SEGV

- .github/workflows/CI.yml
ruby/setup-ruby is the repo with the custom action that loads Ruby and sets up the environment for it.
When PR #727 was done, several updates to ruby/setup-ruby were not yet merged. MSP-Greg/ruby-setup-ruby contained many of those updates, so CI was switched to that.
ruby/setup-ruby is now working with Windows-2022 image, so switch back to it.
> CI.yml - back to ruby/setup-ruby

- ext/oj/string_writer.c
> Fix typo in the comment

- ext/oj/dump.h
Better performance in filling indent by using standard C function if the indentation is deep.
- macOS
−       | before   | after  | result
--       | --       | --     | --
indent 0 | 1.181M   | 1.180M | −
indent 2 | 1.065M   | 1.033M | 0.970x
indent 4 | 976.918k | 1.022M | 1.046x
indent 8 | 795.413k | 1.030M | 1.295x
- Linux
−       | before | after  | result
--       | --     | --     | --
indent 0 | 1.398M | 1.389M | −
indent 2 | 1.243M | 1.252M | 1.007x
indent 4 | 1.165M | 1.245M | 1.069x
indent 8 | 1.025M | 1.234M | 1.204x
- macOS
- macOS 12.3 beta
- Apple M1 Max
- Apple clang version 13.1.6 (clang-1316.0.20.6)
- Ruby 3.1.1
- Linux
- Kubuntu 21.10
- gcc version 11.2.0
- Ruby 3.1.1
```
indent 0   118.606k i/100ms …
```
> Improve indentation performance

- ext/oj/code.c
- ext/oj/custom.c
- ext/oj/dump.c
- ext/oj/dump.h
- ext/oj/dump_compat.c
- ext/oj/dump_leaf.c
- ext/oj/dump_object.c
- ext/oj/dump_strict.c
- ext/oj/oj.h
- ext/oj/rails.c
It has a slightly better performance to copy characters by using standard C function
−       | before   | after    | result
--       | --       | --       | --
macOS    | 363.396k | 377.166k | 1.038x
Linux    | 347.901k | 354.864k | 1.020x
- macOS
- macOS 12.3 beta
- Apple M1 Max
- Apple clang version 13.1.6 (clang-1316.0.20.6)
- Ruby 3.1.1
- Linux
- Kubuntu 21.10
- gcc version 11.2.0
- Ruby 3.1.1
```
Oj.dump     36.222k i/100ms
Oj.dump     363.396k (± 0.4%) i/s -      7.281M in  20.035345s
```
```
Oj.dump     37.656k i/100ms
Oj.dump     377.166k (± 0.4%) i/s -      7.569M …
```
> Use standard C function to copy characters

- ext/oj/dump.c
GCC 12 reports use-after-free warning at compilation.
```
dump.c: In function ‘oj_write_obj_to_file’:
dump.c:627:19: warning: pointer ‘f’ may be used after ‘fclose’ [-Wuse-after-free]
627 |         int err = ferror(f);
|                   ^~~~~~~~~
dump.c:625:5: note: call to ‘fclose’ here
625 |     fclose(f);
|     ^~~~~~~~~
```
This patch will fix this warning.
> Fix use-after-free in file pointer

- ext/oj/fast.c
- ext/oj/mimic_json.c
- ext/oj/oj.c
- ext/oj/string_writer.c
Replace incorrect stack constant with BUFFER_EXTRA macro as a quick fix to the full PR. See https://github.com/ohler55/oj/pull/757#issuecomment-1120103857.
> Use BUFFER_EXTRA constant where required

- ext/oj/dump.c
- ext/oj/dump.h
- ext/oj/dump_leaf.c
- ext/oj/fast.c
- ext/oj/mimic_json.c
- ext/oj/oj.c
- ext/oj/oj.h
- ext/oj/rails.c
- ext/oj/string_writer.c
Currently there are quite a few places where a stack allocated buffer of `N + 10` bytes are allocated instead of `N + 64`. This can become problematic when the buffer is grown and `N + 64` bytes are read, causing the application to read past the actual buffer bounds.
As there are quite a few places where these allocations occur, I've tried to abstract over them by creating the functions `oj_out_init_*` for various stack and heap allocations, as well as an `oj_out_free` function for performing the cleanup. I have placed them in dump.c but there may be a more preferable place to put them. I also did some other small refactoring where I saw that existing functions can be reused.
I am submitting this patch on behalf of Oracle.
> Fix buffer allocation/grow problem and refactor buffer code.

- .github/workflows/CI.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- CHANGELOG.md
- ext/oj/dump.c
Fixes #761.
Remove accidentally committed debug output statement.
> Don't flood stdout with debug output

- oj.gemspec
Since removing the `.travis.yml` file and migrating to GitHub actions,
this dependency is no longer used. (At least that's my assumption.)
> Remove `wwtd` dependency

- ext/oj/mimic_json.c
- test/json_gem/json_generator_test.rb
`nil` is a valid second argument to `JSON.pretty_generate`, in fact, it's the [default](https://github.com/flori/json/blob/5d9d8f3799f2f65ebaa7b485fd6078ce5c79818c/lib/json/common.rb#L390).
As a user of the `oj` gem, I would expect that after invoking `Oj.mimic_JSON`, this argument would still be valid.
However, at least on the current version (I didn't check earlier versions), a mimicked `JSON.pretty_generate` crashes ruby with a segmentation fault inside `oj_mimic_pretty_generate`.
This PR's first commit adds a test for this, which on my laptop ("ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]") also crashes with a segfault.
The second commit adds a check to `oj_mimic_pretty_generate` to handle a `nil` second argument exactly as if there were no second argument. I think I …
> Accept `nil` for `opts` in `pretty_generate`

- ext/oj/dump.c
We encountered a segfault by dumping json in certain conditions. There seems to be an obsolete fclose which is likely caused by a merge / rebase fault.
Backtrace:
```gdb
#0  0x00007f00b459a00b in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f00b4579859 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f00b45e426e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f00b45ec2fc in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007f00b45edf6d in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007f00b45d8ec3 in fclose () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007f00b001541e in oj_write_obj_to_file (obj=93852459311840, path=<optimized out>, copts=copts@entry=0x7ffd9c5debb0) at dump.c:624
#7  0x00007f00b002c9f6 in to_file (argc=<optimized out>, …
```
> dump: Fix double free in oj_write_obj_to_file

- oj.gemspec
Seems that `test_files` attribute has been deprecated.
If we can remove it from gemspec file, it would reduce distribute gem package size.
Related:
- https://github.com/rubygems/guides/issues/90
- https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecdeprecatedattributeassignment
> Remove test_files to reduce gem package size

- ext/oj/mimic_json.c
- test/json_gem/json_parser_test.rb
Fix https://github.com/ohler55/oj/issues/770
Revert max_nesting behavior to v3.13.9, however, this behavior is not compatible with Ruby standard JSON gem.
> Revert max_nesting behavior when max_nesting option was not given

- ext/oj/oj.c
- ext/oj/sparse.c
- test/test_file.rb
Seems that it need to convert file path to wide char to handle unicode file path on Windows using [MultiByteToWideChar ](https://docs.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-multibytetowidechar)
rb_w32_mbstr_to_wstr() will convert it well.
Fix https://github.com/ohler55/oj/issues/772
> Convert file path to wide char to handle unicode file path on Windows

- ext/oj/mimic_json.c
Implicit mode change might affect `Oj.dump` / `Oj.load`, so I propose to warn user on this change:
```ruby
require 'oj'
Oj.generate 'hello'
```
> Warn on implicit Oj::Rails.mimic_JSON

- ext/oj/dump.c
- ext/oj/oj.c
- ext/oj/oj.h
- test/test_various.rb
Similar to https://github.com/flori/json/pull/405
It's a "cheap" way to make JSON safe to interpolate in a `<script>` tag.
> Implement `:escape_mode => :slash`

- ext/oj/dump.c
- ext/oj/dump_compat.c
- ext/oj/dump_object.c
- ext/oj/extconf.rb
- ext/oj/oj.c
- ext/oj/oj.h
- ext/oj/rails.c
- ext/oj/wab.c
Currently, Oj gem supports Ruby 2.4 or later.
https://github.com/ohler55/oj/blob/f1e77489e03f0a47bdf296eac29e9b8d9b663d32/oj.gemspec#L23
Oj has been checking Ruby C APIs presence in extconf.rb, 
however, I think the some APIs are definitely present and can be checked off.
- rb_time_timespec
- Since 1.9.3
- Commit https://github.com/ruby/ruby/commit/92cb7d0ad49d5c681119471862698d9de00bd1a6
- rb_ivar_count
- Since 1.9.2
- Commit https://github.com/ruby/ruby/commit/1cc1ea378a0912bfcbe55399369da47a724427aa
- rb_ivar_foreach
- Since 1.9.0
- https://github.com/ruby/ruby/commit/5c0e68c39c3fc7717311826549a30d1615eb2007
- rb_enc_associate
- Since 1.9.0
- https://github.com/ruby/ruby/commit/000b6e22f463c560f695b460272395a492eface5
> Remove some checking Ruby C APIs presence

- ext/oj/extconf.rb
- ext/oj/parse.c
- test/test_compat.rb
In the case of long strings, it takes time to scan the string up to double quotes.
So, this patch will introduce SIMD instructions to improve the performance.
−            | before | after  |  result
--            | --     | --     | --
Oj.load   [0] | 4.131M | 4.153M | 1.005x
Oj.load  [64] | 3.244M | 3.591M | 1.107x
Oj.load [128] | 2.829M | 3.382M | 1.195x
- Linux
- Kernel: 5.18.0-1-rt11-MANJARO
- Ruby 3.1.2
```
Oj.load   [0]   413.265k i/100ms
Oj.load  [64]   326.361k i/100ms
Oj.load [128]   283.154k i/100ms
Oj.load   [0]      4.131M (± 0.2%) i/s -     82.653M in  20.007292s
Oj.load  [64]      3.244M (± 0.6%) i/s - …
```
> Use SSE 4.2 due to scan string in read_str()

- ext/oj/parse.c
This will fix following error.
```
compiling ../../../../ext/oj/parse.c
../../../../ext/oj/parse.c:366:28: error: too many arguments to function call, expected single argument 'pi', have 2 arguments
scan_string_noSIMD(pi, str);
~~~~~~~~~~~~~~~~~~     ^~~
../../../../ext/oj/parse.c:330:20: note: 'scan_string_noSIMD' declared here
static inline void scan_string_noSIMD(ParseInfo pi) {
```
When I made various changes along the way, I forgot to fix argument in https://github.com/ohler55/oj/pull/783 
Sorry
> Fix build error on non SSE 4.2 environment

- ext/oj/compat.c
- ext/oj/custom.c
- ext/oj/object.c
- ext/oj/strict.c
- ext/oj/wab.c
I think that `Yes == pi->options.trace` will be false in most cases.
If the compiler supports it, the UNLIKELY hint might speed up the conditional branching slightly.
−       | before   | after   | result
--       | --       | --      | --
Oj.load  | 374.821k |383.001k | 1.022x
- Linux
- Kernel: 5.18.0-1-rt11-MANJARO 
- Ruby 3.1.2
```
Oj.load    37.784k i/100ms
Oj.load    374.821k (± 0.5%) i/s -      7.519M in  20.060807s
```
```
Oj.load    38.599k i/100ms
Oj.load    383.001k (± 0.5%) i/s -      7.681M in  20.055707s
```
```ruby …
```
> Add RB_UNLIKELY hint for tracing log

- ext/oj/buf.h
- ext/oj/parse.c
- test/test_compat.rb
This patch will introduce SIMD instructions to improve the performance where the escaped string is parsed
using the same technique as https://github.com/ohler55/oj/pull/783
−       | before | after  | result
--       | --     | --     | --
Oj.load  | 1.530M | 2.052M | 1.341x
- Linux
- Kernel: 5.18.0-1-rt11-MANJARO
- Ruby 3.1.2
```
Oj.load   153.339k i/100ms
Oj.load      1.530M (± 0.4%) i/s -     15.334M in  10.025542s
```
```
Oj.load   205.971k i/100ms
Oj.load      2.052M (± 0.3%) i/s -     20.597M in  10.037144s
```
```ruby …
```
> Use SSE 4.2 due to parse escaped string

- ext/oj/extconf.rb
https://github.com/ohler55/oj/issues/789
SSE4.2 instructions will not be used when it causes SEGV during configuration.
> Enable the SSE4.2 flag only when the compiled executable file works properly

- ext/oj/parse.c
There are several branches in the loop that parse Integer string.
In order to speed up parsing, this patch will move unwanted branches out of the loop.
−       | before | after  | result
--       | --     | --     | --
integer  | 4.860M | 5.088M | 1.045x
float    | 4.845M | 5.084M | 1.049x
- Linux
- Kernel: 5.18.12-3-MANJARO
- Ruby 3.1.2
```
Oj.load integer   488.037k i/100ms
Oj.load float   485.863k i/100ms
Oj.load integer      4.860M (± 0.1%) i/s -     48.804M in  10.042684s
Oj.load float      4.845M (± 0.3%) i/s -     48.586M in  10.028592s
```
```
Oj.load integer   508.044k …
```
> Simplify the loop for parsing Integer string

- ext/oj/custom.c
- ext/oj/dump.c
- ext/oj/dump_compat.c
- ext/oj/dump_object.c
- ext/oj/dump_strict.c
- ext/oj/rails.c
- ext/oj/wab.c
If the compiler supports it, the UNLIKELY hint might speed up the conditional branching slightly.
Ref. https://github.com/ohler55/oj/pull/782
−       | before  | after   | result
--       | --      | --      | --
Oj.dump  | 11.754M | 11.775M | -
- Linux
- Kernel: 5.18.12-3-MANJARO
- Ruby 3.1.2
```
Oj.dump     1.166M i/100ms
Oj.dump     11.754M (± 0.2%) i/s -    177.254M in  15.080998s
```
```
Oj.dump     1.184M i/100ms
Oj.dump     11.775M (± 0.2%) i/s -    177.612M in  15.084141s
```
```ruby
require 'benchmark/ips'
require 'oj' …
```
> Add RB_UNLIKELY hint in dump method for tracing log

- ext/oj/extconf.rb
- ext/oj/oj.c
- ext/oj/parse.c
- ext/oj/parse.h
If SSE 4.2 is not available on the system, don't attempt to use SIMD instructions.
Relates to https://github.com/ohler55/oj/issues/789
> Perform runtime check for SSE 4.2 instructions

- ext/oj/saj2.c
Previously if `add_big_*()` were called, Ruby code would seg fault:
```
-- C level backtrace information -------------------------------------------
/opt/gitlab/embedded/lib/libruby.so.2.7(rb_vm_bugreport+0x561) [0x7ff955dd2da1] vm_dump.c:755
[0x7ff955bf5e61]
/opt/gitlab/embedded/lib/libruby.so.2.7(sigsegv+0x59) [0x7ff955d2eca9] signal.c:946
/lib/x86_64-linux-gnu/libc.so.6(0x7ff9559700c0) [0x7ff9559700c0]
/opt/gitlab/embedded/lib/libruby.so.2.7(rb_id_table_lookup+0x7) [0x7ff955d6e727] symbol.h:72
/opt/gitlab/embedded/lib/libruby.so.2.7(lookup_method_table+0x14) [0x7ff955da6a5c] vm_method.c:188
/opt/gitlab/embedded/lib/libruby.so.2.7(method_entry_get) vm_method.c:747
/opt/gitlab/embedded/lib/libruby.so.2.7(rb_callable_method_entry+0x20) [0x7ff955daea70] vm_method.c:891 …
```
> Fix seg faults in SAJ parser

- ext/oj/parse.h
Ensure the parameters are void to be consistent with the implementation.
This was identified in https://github.com/ohler55/oj/issues/796.
> Fix oj_scanner_init prototype

- test/test_parser_saj.rb
> Add test for seg faults in SAJ parser

- test/helper.rb
- test/json_gem/test_helper.rb
- test/test_object.rb
The Ruby interpreter deprecated the `double_heap` option in favor of
`expand_heap` (https://github.com/ruby/ruby/commit/a6dd859affc42b667279e513bb94fb75cfb133c1).
> Fix Ruby garbage collection deprecation warning

- ext/oj/parse.c
On platforms where `USE_SSE_DETECT` is not defined, the compiler may
flag a warning:
```
compiling ../../../../ext/oj/parse.c
../../../../ext/oj/parse.c:240:5: warning: 'USE_SSE_DETECT' is not defined, evaluates to 0 [-Wundef]
^
../../../../ext/oj/parse.c:252:5: warning: 'USE_SSE_DETECT' is not defined, evaluates to 0 [-Wundef]
^
2 warnings generated.
```
> Fix some compiler warnings with USE_SSE_DETECT

- ext/oj/parse.c
- test/test_gc.rb
When we use volatile qualifier, seems it has some performance penalty on GCC.
The volatile qualifier is unnecessary since the VALUE type object has been kept on the local stack.
(If we manage VALUE on the heap, we need to be careful.)
−       | before  | after   | result
--       | --      | --      | --
GCC      | 4.969M  | 5.165M  | 1.039x
Clang    | 5.054M  | 5.090M  | -
- Linux
- Kernel: 5.18.12-3-MANJARO
- clang version 14.0.6
- Ruby 3.1.2
```
Oj.load   497.783k i/100ms
Oj.load      4.969M (± 0.1%) i/s -     49.778M in  10.017042s
```
```
Oj.load   518.127k i/100ms …
```
> Remove unnessary volatile qualifier in Oj.load

- ext/oj/extconf.rb
- ext/oj/parse.c
Compiling with `-msse4.2` is problematic because it may cause a number
of other SSE instructions to be used. For example:
```
$ ./elfx86exts oj.so
MODE64 (call)
CMOV (cmovne)
SSE2 (movq)
SSE41 (pinsrq)
SSE1 (movups)
SSSE3 (pshufb)
SSE3 (movddup)
SSE42 (pcmpestri)
CPU Generation: Unknown
```
The runtime check in #795 is therefore not sufficient to prevent SSE
instructions from leaking elsewhere in the shared library. As a
result, loading Oj on older machines with these libraries will result
in a "illegal instruction" crash.
Introduce a `--with-sse42` flag that can be used to configure this
gem.
> Disable SSE 4.2 compile instructions by default

- pages/Compatibility.md
Now, Oj has been supported ruby 2.4 or later.
https://github.com/ohler55/oj/blob/72d5565c291ee59f8636f37f810a39bdeaad2696/oj.gemspec#L23
> Update ruby version compatibility in document

- ext/oj/saj2.c
- test/test_parser_saj.rb
This seg fault only occurred if the SAJ parser handler tracked locations of hashes with Bignum values with inputs such as:
```json
{
"width": 192.33800000000002,
"xaxis": {
"anchor": "y"
}
}
```
This was missed in #799.
> Fix another seg fault in SAJ parser

- ext/oj/object.c
This change allows exceptions to be create on TruffleRuby with the correct message and backtrace information. I haven't removed the skip on the test this affects as it also requires `rb_ivar_foreach` to be implemented, and that change for TruffleRuby has not been merged yet.
> Create exceptions in a more platform independent way.

- .github/workflows/CI.yml
- Rakefile
- lib/oj/state.rb
- test/json_gem/json_generator_test.rb
- test/json_gem/json_parser_test.rb
- test/test_custom.rb
- test/test_file.rb
- test/test_gc.rb
- test/test_object.rb
- test/test_scp.rb
- test/test_various.rb
From https://github.com/oracle/truffleruby/issues/2701 and https://github.com/ohler55/oj/pull/804.
Now the only skips on TruffleRuby are the 3 `test_deep_nest` and `CustomJuice#test_time` (different rounding).
> Remove most skips on TruffleRuby

- test/test_object.rb
- test/tests.rb
- test/tests_mimic.rb
- test/tests_mimic_addition.rb
Since Ruby 3.2.0, `GC.verify_compaction_references` has the change.
https://github.com/ruby/ruby/commit/a6dd859affc42b667279e513bb94fb75cfb133c1
If `expand_heap` is present, It will certainly try to expand the heap area on each calling.
We are calling it many time on `teardown`, and then Ruby process try to allocate a large amount of memory.
When a large amount of memory space is allocated, it takes a very long time to expand it at next time.
Finally, the test fails with a timeout on CI.
I think it would be sufficient to perform GC validation on survived object at end of process.
This change should eliminate failures on Ruby 3.2 CI lane.
> Move GC verification to end of process in tests

- ext/oj/parser.c
This patch will suppress following warning message when compile oj with GCC 12.
```
$ cd ext/oj
$ ruby extconf.rb
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object …
```
> Suppress "old style definition" warning

- ext/oj/parse.c
This patch will fix follwing build error at installation:
```
$ gem install oj -- --with-sse42
Building native extensions with: '--with-sse42'
This could take a while...
ERROR:  Error installing oj:
ERROR: Failed to build gem native extension.
current directory: /home/watson/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/oj-3.13.23/ext/oj
/home/watson/.rbenv/versions/3.1.3/bin/ruby -I /home/watson/.rbenv/versions/3.1.3/lib/ruby/3.1.0 extconf.rb --with-sse42
>>>>> Creating Makefile for ruby version 3.1.3 on x86_64-linux <<<<<
checking for rb_gc_mark_movable()... yes
checking for stpcpy()... yes
checking for pthread_mutex_init()... yes
checking for rb_enc_interned_str()... yes
checking for rb_ext_ractor_safe() in ruby.h... yes
checking for rb_hash_bulk_insert() in ruby.h... yes
creating …
```
> Fix build error with SSE 4.2 flag

- README.md
- ext/oj/compat.c
- ext/oj/custom.c
- ext/oj/dump.c
- ext/oj/dump_compat.c
- ext/oj/dump_object.c
- ext/oj/dump_strict.c
- ext/oj/extconf.rb
- ext/oj/object.c
- ext/oj/rails.c
- ext/oj/strict.c
- ext/oj/trace.h
- ext/oj/wab.c
- pages/InstallOptions.md
I think the trace log feature is for debugging and most people don't use it. Therefore, I usually want to improve performance by removing unnecessary instructions.
−       | before | after  | result
--       | --     | --     | --
Oj.dump  | 1.440M | 1.697M | 1.178x
- Linux
- Kernel: 6.1.1-1-MANJARO
- AMD Ryzen 7 5800H
- gcc version 12.2.0
- Ruby 3.2.0
```
Oj.dump   142.510k i/100ms
Oj.dump      1.440M (± 0.4%) i/s -     14.536M in  10.091795s
```
```
Oj.dump   165.140k i/100ms
Oj.dump      1.697M (± 0.7%) i/s -     17.009M in  10.025122s
```
```ruby
require …
```
> Add --enable-trace-log install option

- ext/oj/extconf.rb
On platform using ARM CPU such as Apple M1/M2, it causes build error (see below logs) with ` --with-sse42`.
So this patch adds a guard for Apple M1/M2.
```
$ gem install pkg/oj-3.14.0.gem -- --with-sse42
Building native extensions with: '--with-sse42'
This could take a while...
ERROR:  Error installing pkg/oj-3.14.0.gem:
ERROR: Failed to build gem native extension.
current directory: /Users/watson/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/oj-3.14.0/ext/oj
/Users/watson/.rbenv/versions/3.2.0/bin/ruby -I /Users/watson/.rbenv/versions/3.2.0/lib/ruby/3.2.0 extconf.rb --with-sse42
>>>>> Creating Makefile for ruby version 3.2.0 on arm64-darwin22 <<<<<
checking for rb_gc_mark_movable()... yes
checking for stpcpy()... yes
checking for pthread_mutex_init()... yes
checking for …
```
> Add a guard for SSE 4.2 feature

- ext/oj/custom.c
- ext/oj/dump.c
- ext/oj/dump_compat.c
- ext/oj/dump_object.c
- ext/oj/dump_strict.c
- ext/oj/oj.h
- ext/oj/rails.c
- ext/oj/reader.c
- ext/oj/wab.c
- test/test_compat.rb
Fix https://github.com/ohler55/oj/issues/834
In Ruby, it can easily override the `to_s` method and it may not return a string as expected (rarely).
This PR will check the object using `StringValue`  whether it is a string object as expected after calling `to_s`.
> Fix SEGV if to_s method returns invalid object

- README.md
This PR will fix following error in built status 
Ref. https://github.com/badges/shields/issues/8671
The URL in this PR was generated by `Create Status badge` in https://github.com/ohler55/oj/actions/workflows/CI.yml
> Update the URL of build status badge in README

- ext/oj/object.c
This macro marks the array as not protected by a write barrier which has negative effects on GC performance.
As far as I could tell, all the uses in Oj are purely for read so we can use `RARRAY_CONST_PTR` which is effectively the same but doesn't unprotect the array.
cc @peterzhu2118
> Avoid using RARRAY_PTR

- ext/oj/dump_compat.c
- test/json_gem/json_generator_test.rb
This patch will raise TypeError exception in JSON.generate if  to_json method returns invalid object to avoid SEGV
```ruby
require 'oj'
Oj.mimic_JSON
class Foo
def to_json
nil
end
end
obj = { foo: Foo.new }
puts JSON.generate(obj)
```
Similar: https://github.com/ohler55/oj/pull/836
> Fix SEGV in JSON.generate if to_json method returns invalid object

- .rubocop_todo.yml
- Rakefile
- test/files.rb
- test/helper.rb
- test/json_gem/json_common_interface_test.rb
- test/json_gem/json_parser_test.rb
- test/perf.rb
- test/perf_file.rb
- test/perf_simple.rb
- test/sample.rb
- test/sample_json.rb
- test/test_compat.rb
- test/test_custom.rb
- test/test_fast.rb
- test/test_file.rb
- test/test_scp.rb
- test/test_strict.rb
- test/test_various.rb
- test/test_wab.rb
Autofix the Lint rules with no options. Fixing the last one I hit a conditional for testing on the old Ruby versions that have been removed, so added a commit to clean those up too
> Autofix Rubocop Lint - Batch 3

- ext/oj/stream_writer.c
When it invoked Data_Wrap_Struct(), Ruby's GC can release allocated memory properly. However, we have to manage the memory ourselves until invoking Data_Wrap_Struct(),
So, we have to release the memory manually before raising exception if it raises the exception before invoking Data_Wrap_Struct().
You will see an increase memory usage with attached test code.
```
0, 17.69140625 MB
1000, 22.37890625 MB
2000, 26.76171875 MB
3000, 31.14453125 MB
4000, 35.52734375 MB
5000, 40.16796875 MB
6000, 44.55078125 MB
7000, 48.93359375 MB
8000, 53.31640625 MB
9000, 57.69921875 MB
```
```
0, 17.69140625 MB
1000, 17.9921875 MB
2000, 17.9921875 MB
3000, 17.9921875 MB
4000, 17.9921875 MB
5000, 17.9921875 MB
6000, 17.9921875 MB
7000, 17.9921875 MB
8000, 17.9921875 MB
9000, 17.9921875 MB
```
```ruby
require …
```
> Fix memory leak in Oj::StreamWriter.new

- ext/oj/mimic_json.c
- lib/oj/easy_hash.rb
- lib/oj/mimic.rb
- test/isolated/shared.rb
- test/test_parser_saj.rb
- test/test_saj.rb
`JSON.create_id=` method accepts `nil` as an argument in document. https://github.com/ohler55/oj/blob/2c1a622660ed5ab94b9fdfbcc7bc16017307972a/ext/oj/mimic_json.c#L655
However, it raises TypeError when passed `nil`.
```
irb(main):001:0> require 'oj'
=> true
irb(main):002:0> Oj.mimic_JSON
=> JSON
irb(main):003:0> JSON.create_id = nil
(irb):3:in `create_id=': wrong argument type nil (expected String) (TypeError)
from (irb):3:in `<main>'                             
from /home/watson/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
from /home/watson/.rbenv/versions/3.2.1/bin/irb:25:in `load'
from /home/watson/.rbenv/versions/3.2.1/bin/irb:25:in `<main>'
irb(main):004:0> 
```
This patch will accept `nil` as an argument.
> Fix JSON.create_id= to allow nil

- ext/oj/dump_leaf.c
- ext/oj/fast.c
- ext/oj/oj.c
- ext/oj/parser.c
- ext/oj/saj.c
- ext/oj/stream_writer.c
- ext/oj/string_writer.c
StringValuePtr() is called after checking the type, but StringValuePtr() also performs type checking.
StringValuePtr() will invoke rb_string_value() which performs Implicit type conversion and type checking.
```
VALUE
rb_string_value(volatile VALUE *ptr)
{
VALUE s = *ptr;
if (!RB_TYPE_P(s, T_STRING)) {
s = rb_str_to_str(s);
*ptr = s;
}
return s;
}
```
> Remove redundant rb_check_type for String

- ext/oj/custom.c
- ext/oj/object.c
- ext/oj/strict.c
- ext/oj/wab.c
I forgot to change these when I was add `-enable-trace-log` install option at https://github.com/ohler55/oj/pull/832.
> Use TRACE_PARSE_CALL() macro for debug log

- ext/oj/mimic_json.c
A few warning messages appear while using `Oj.optimize_rails` with `$VERBOSE = true`
Here they are:
```
.../config/application.rb:23: warning: method redefined; discarding old create_id=
/Users/vasyldubinchyk/.rvm/gems/ruby-3.1.3/gems/json-2.6.2/lib/json/common.rb:120: warning: previous definition of create_id= was here
.../config/application.rb:23: warning: method redefined; discarding old create_id
/Users/vasyldubinchyk/.rvm/gems/ruby-3.1.3/gems/json-2.6.2/lib/json/common.rb:126: warning: previous definition of create_id was here
.../config/application.rb:23: warning: method redefined; discarding old dump
/Users/vasyldubinchyk/.rvm/gems/ruby-3.1.3/gems/json-2.6.2/lib/json/common.rb:631: warning: previous definition of dump was here
.../config/application.rb:23: warning: method …
```
> Hide method redefined warnings

- ext/oj/extconf.rb
- ext/oj/fast.c
Currently the oj gem supports Ruby 2.7+.
rb_gc_mark_movable() has introduced at Ruby 2.7.
Ref. https://github.com/ruby/ruby/blob/v2_7_0/include/ruby/intern.h#L540
So, we can use rb_gc_mark_movable() freely in oj gem.
> Remove checking whether rb_gc_mark_movable exists

- ext/oj/extconf.rb
- ext/oj/fast.c
Reverts ohler55/oj#876
Because truffleruby caseus following error about `rb_gc_mark_movable`.
Hmm, it has something changes in truffleruby head, maybe...
```
DocTest#test_open_close:
RuntimeError: Wrapped undumpable exception for: Polyglot::ForeignException: External LLVMFunction rb_gc_mark_movable cannot be found.
/home/runner/work/oj/oj/ext/oj/fast.c:694:in `mark_doc'
<internal:core> core/truffle/polyglot.rb:334:in `<unknown>'
<internal:core> core/truffle/polyglot.rb:334:in `Truffle::Interop.execute'
<internal:core> core/truffle/polyglot.rb:334:in `Polyglot::ExecutableTrait#call'
/home/runner/.rubies/truffleruby-23.0.0-preview1/lib/truffle/truffle/cext.rb:1520:in `CExt#run_marker'
/home/runner/.rubies/truffleruby-23.0.0-preview1/lib/truffle/truffle/cext_ruby.rb:41:in `Oj::Doc.open' …
```
> Revert "Remove checking whether rb_gc_mark_movable exists"

- ext/oj/dump.c
- test/test_compat.rb
To convert an Integer to a String, it needs to do division and remainder calculations many times. These calculations can consume more CPU cycles than other instructions.
This patch will prepare a lookup table which has the remainder (0~99) of a number divided by 100 and use the table to omit the calculation.
−       | before  | after   | result
--       | --      | --      | --
Oj.dump  | 3.816M  | 4.255M  | 1.115x
- Linux
- Kernel: 6.3.0-1-MANJARO
- AMD Ryzen 7 5800H
- gcc version 12.2.1
- Ruby 3.2.2
```
Oj.dump   386.110k i/100ms
Oj.dump      3.816M (± 1.4%) i/s -     19.306M in   5.060327s
```
```
Oj.dump   425.525k …
```
> Optimize integer value dumps

- docs/mode_table.html
- ext/oj/dump.c
- ext/oj/mimic_json.c
- ext/oj/oj.c
- ext/oj/oj.h
- pages/Options.md
- test/test_custom.rb
- test/test_various.rb
Closes: #882 
See https://github.com/ohler55/oj/issues/882
- A `:skip_null_byte` boolean option is introduced. If set to `true`, null bytes will be omitted from strings when dumping.
- Documentation is updated (`docs/mode_table.html` and `Pages/Options.md`)
```rb
Oj.dump({ "key\x00" => "val\x00ue" }, :skip_null_byte => true)
```
> Enable optional skipping of null bytes on dump

- ext/oj/code.c
- ext/oj/dump.c
- ext/oj/dump.h
- ext/oj/fast.c
- ext/oj/oj.h
Refactor converting number to string by using optimized function which introduced at https://github.com/ohler55/oj/pull/879
> Refactor converting number to string by using optimized function

- ext/oj/compat.c
- ext/oj/custom.c
- ext/oj/parse.c
Refactor in where obtain hash keys by using common function. However, it might have the margin of error for the overhead of calling oj_calc_hash_key().
−       | before   | after    | result
--       | --       | --       | --
Oj.dump  | 449.521k | 447.738k | 0.996x
- Linux
- Kernel: 6.3.5-2-MANJARO
- AMD Ryzen 7 5800H
- gcc version 13.1.1
- Ruby 3.2.2
```
Oj.load    44.738k i/100ms
Oj.load    449.521k (± 0.9%) i/s -      6.755M in  15.029388s
```
```
Oj.load    44.117k i/100ms
Oj.load    447.738k (± 0.3%) i/s -      6.750M in  15.075672s
```
```ruby
require …
```
> Refactor in where obtain hash keys by using common function

- oj.gemspec
The bigdecimal gem will be changed bundled gem since Ruby 3.4.0.
https://www.ruby-lang.org/en/news/2023/09/14/ruby-3-3-0-preview2-released/
To use bundled gem, it requires to specify the dependency in Gemfile.
This patch will fix following warning with Ruby 3.3.0-preview2.
```
/Users/watson/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/oj-3.16.1/lib/oj/mimic.rb:3: warning: bigdecimal will be not part of the default gems since Ruby 3.4.0. Add bigdecimal to your Gemfile. Also contact author of  to add bigdecimal into its gemspec.
```
> Add bigdecimal as dependency gem

- ext/oj/cache.c
- ext/oj/cache.h
- ext/oj/dump.c
- ext/oj/fast.c
- ext/oj/intern.c
- ext/oj/oj.h
- ext/oj/parser.c
- ext/oj/rails.c
- ext/oj/stream_writer.c
- ext/oj/string_writer.c
- ext/oj/val_stack.c
The replacement API was introduced in Ruby 1.9.2 (2010),
and the old untyped data API was marked a deprecated in the documentation
as of Ruby 2.3.0 (2015)
Ref: https://bugs.ruby-lang.org/issues/19998
I made the minimal migration, which simply use `TypedData`, but it open the door to enable many GC features such as write barriers, immediate free, compaction support etc. But to avoid accidentally introducing any bugs I didn't do any of that, I kept changes the minimum.
On a side note I noticed this:
```c
if (given || 0 != ex) {
DATA_PTR(doc->self) = NULL;
// TBD is this needed?
/*
doc_free(pi.doc);
if (0 != ex) {  // will jump so caller will not free
OJ_R_FREE(json);
}
*/
```
To answer the comment, yes this is most definitely a memory leak, but it's unclear to me why the data pointer is …
> Stop using the deprecated `Data_*` API

- ext/oj/extconf.rb
- ext/oj/usual.c
`rb_hash_bulk_insert` function can be used as public API since Ruby 2.7.0. https://github.com/ruby/ruby/commit/d3df725f9efeb0e6c121f9a1316abaa90956f1b8
Current Oj gem only supports Ruby 2.7.0 or later.
So there is no need to check whether function exists.
> Clean up HAVE_RB_HASH_BULK_INSERT

- ext/oj/dump.c
- test/activesupport6/encoding_test.rb
- test/activesupport7/encoding_test.rb
This is a potential fix for https://github.com/ohler55/oj/issues/911. Currently, whether or not `Oj::Rails::Encoder` raises on invalid unicode data depends on the value of `ActiveSupport.escape_html_entities_in_json`. In order to accurately mimic the behaviour of stock Rails with the stock json gem, it should in fact raise an exception regardless.
I've so far deliberately copied rather than shared functionality that's shared between `RailsEsc` and `RailsXEsc` mode, because I wasn't quite sure how to factor the similarities out. We can leave it like this, or I'm happy to take pointers on a way to factor this down better.
I added a testcase for invalid Unicode to the Rails 6 & 7 encoding tests, and also parameterised the existing unicode-related tests to make sure they work correctly with …
> Make invalid Unicode data raise when encoding through Oj::Rails::Encoder

- gemfiles/rails_6.1.gemfile
- gemfiles/rails_7.gemfile
This patch will fix https://github.com/ohler55/oj/actions/runs/7908156404/job/21586745798
Some gems using CI will be changed bundled gem since Ruby 3.4.0. To use bundled gem, it requires to specify the dependency in Gemfile.
Ref. https://github.com/ohler55/oj/pull/901
> CI: Add to dependency what to migrate to bundle gem in Ruby 3.4

- lib/oj/schandler.rb
These two descriptions were flip-flopped. I also added some parenthesis after hash_key(), to make it more consistent with the other items.
> Fix ScHandler docs

- ext/oj/extconf.rb
- ext/oj/fast.c
- ext/oj/parser.h
- ext/oj/reader.c
- ext/oj/saj.c
This change adds WebAssembly/WASI target support for the extension library. Right now, we don't have an easy way to set up CI to test it, but we would appreciate it if we could merge the change into the upstream.
I manually tested it works well on my end.
> Port to WASI by adding a check for getrlimit

- Rakefile
Since Ruby-HEAD fails to load some gems, this patch gives `bundle exe` so that gems are loaded via bundler.
The following errors will be resolved:
> CI: Use `bundle exe` to run each test files in order to solve CI error

- lib/oj/mimic.rb
- oj.gemspec
The ostruct gem will be changed bundled gem since Ruby 3.5.0. https://github.com/ruby/ruby/commit/4db7c8a24ad66e15ef6bce053c4d5d90b84cb855
The ostruct gem has been required at https://github.com/ohler55/oj/blob/2e57dc711172ee2aae4a1e381ad905c7d461e805/lib/oj/json.rb#L1
To use bundled gem, it requires to specify the dependency in Gemfile.
Similar with https://github.com/ohler55/oj/pull/901
> Add ostruct as dependency gem for Ruby 3.5

- ext/oj/mimic_json.c
- ext/oj/rails.c
Fix: https://github.com/ruby/json/issues/672
GC compaction might move these objects around so the global C variable MUST be declared to the GC so it's updated there too.
> Properly declare global variables

- ext/oj/stream_writer.c
- test/test_writer.rb
Don't use write(2) for writing to file descriptors, use IO::write instead just as for writing to a non-file IO.
Using write(2) means having to handle all kinds of edge cases, such as EINTR and EAGAIN/EWOULDBLOCK, and doesn't release the GVL when blocking.
Fixes #943
> Fix streaming to file descriptor

- ext/oj/parse.c
This patch will sort the conditional statements to reduce the conditional branches by skipping if statements that do not need to be executed depending on the value of `first`.
−       | before   | after    | result
--      | --       | --       | --
Oj.load | 325.594k | 341.356k | 1.048x
- Linux
- Kernel: 6.12.4-1-MANJARO
- AMD Ryzen 9 8945HS
- gcc version 14.2.1
- Ruby 3.4.1
```ruby
require 'bundler/inline'
gemfile do
source 'https://rubygems.org'
gem 'benchmark-ips'
gem 'oj'
end
json = '{"a":"Alpha","b":true,"c":12345,"d":[true,[false,[-123456789,null],3.9676,["Something else.",false],null]],"e":{"zero":null,"one":1,"two":2,"three":[3],"four":[0,1,2,3,4]},"f":null,"h":{"a":{"b":{"c":{"d":{"e":{"f":{"g":null}}}}}}},"i":[[[[[[[null]]]]]]]}'
Benchmark.ips do |x| …
```
> Sort the conditional statements

- test/perf_strict.rb
`JSON.parse(@json, symbolize_names: @symbolize)` allocates an extra hash, which isn't necessary when `symbolize` is `false`.
In the grand scheme of things, it's not a big deal, but on this sort of micro-benchmarks that can easily accound for a huge part of the runtime just because of the increased GC pressure.
> bench: Avoid allocating an extra hash when not necessary

- ext/oj/fast.c
- ext/oj/mimic_json.c
- ext/oj/oj.c
- ext/oj/parse.c
- ext/oj/rails.c
- ext/oj/saj.c
- ext/oj/scp.c
- ext/oj/stream_writer.c
- ext/oj/strict.c
- ext/oj/string_writer.c
This patch will use rb_utf8_str_new/rb_utf8_str_new_cstr API to create UTF8 string.
Seems it has slightly better performance.
−       | before  | after   | result
--      | --      | --      | --
Oj.load | 654.004 | 670.792 | 1.025x
- Linux
- Kernel: 6.12.4-1-MANJARO
- AMD Ryzen 9 8945HS
- gcc version 14.2.1
- Ruby 3.4.1
```ruby
require 'bundler/inline'
gemfile do
source 'https://rubygems.org'
gem 'benchmark-ips'
gem 'oj'
end
json = File.read('twitter.json')
Benchmark.ips do |x|
x.time = 10
x.report('Oj.load compat') { Oj.load(json, mode: :compat) }
end
```
```
$ ruby json_load.rb
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [x86_64-linux]
Oj.load compat    64.000 i/100ms
Calculating …
```
> Use rb_utf8_str_new/rb_utf8_str_new_cstr to create UTF8 string

- oj.gemspec
Closes #951
Follows up to #771
This aims to reduce the gem package size by removing test files from a built gem.
> Remove test files to reduce gem size

- test/json_gem/json_ext_parser_test.rb
- test/json_gem/json_generator_test.rb
Recently Ruby HEAD has some changes in JSON and it causes failures in tests.
Ref. https://github.com/ohler55/oj/actions/runs/13188779428
Since https://github.com/ruby/ruby/commit/599fbeaffa, it causes failure in test_allocate
```
=========================================================================================================================================================================================================================================
Failure: test_allocate(JSONExtParserTest):
[ruby-core:35079].
<TypeError> exception was expected but none was thrown.
test/json_gem/json_ext_parser_test.rb:14:in 'JSONExtParserTest#test_allocate'
11:   if defined?(JSON::Ext::Parser)
12:     def test_allocate
13:       parser = JSON::Ext::Parser.new("{}")
=> 14: …
```
> CI: Fix failures with Ruby 3.5-dev

- ext/oj/parser.c
- ext/oj/parser.h
This is required for the Oj::Introspect parser.
> Expose `oj_parser_type` for extensions

- ext/oj/dump.c
- ext/oj/dump.h
- ext/oj/oj.c
- ext/oj/simd.h
This PR uses ARM Neon instruction to accelerate the `hibit_friendly_size` function. This same technique can be applied to the other `*_friendly_size` functions.
Would love your thoughts if this is something to pursue further.
These benchmarks use the [this benchmark](https://github.com/ruby/json/blob/master/benchmark/encoder.rb#L78) from the [ruby/json](https://github.com/ruby/json/) project.
```
== Encoding mixed utf8 (5003001 bytes)
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [arm64-darwin24]
oj    35.000 i/100ms
oj    341.918 (± 4.1%) i/s    (2.92 ms/i) -      1.715k in   5.024382s
```
According to this call tree generated by [samply](https://github.com/mstange/samply) the …
> Use ARM Neon instructions to accelerate hibit_friendly_size.

- ext/oj/dump.c
[This PR](https://github.com/ohler55/oj/pull/963) had a bug. Spending 0.1% of time in the `hibit_friendly_size` seemed too good to be true. I forgot to increment `str` in the loop...
After this fix we spend about 11% or so of time in the `hibit_friendly_size`. It's still a good improvement.
The performance mostly holds though.
```
== Encoding mixed utf8 (5003001 bytes)
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [arm64-darwin24]
oj    54.000 i/100ms
oj    509.722 (± 5.3%) i/s    (1.96 ms/i) -      2.592k in   5.099497s
```
> ARM Neon `hibit_friendly_size` bugfix.

- ext/oj/dump.c
- test/test_long_strings.rb
- test/tests.rb
Note: This contains the bugfix from [this PR](https://github.com/ohler55/oj/pull/965).
Optimizing `Oj.dump(str, mode: :rails)`
The two benchmarks:
```
benchmark_encoding "mixed utf8", ([("a" * 5000) + "€" + ("a" * 5000)] * 500)
benchmark_encoding "ascii", ([("a" * 5000) + ("a" * 5000)] * 500)
```
The `€` triggers the `has_hi` so the speedup is quite different between the two benchmarks. The `mixed utf8` benchmark is a small speedup as the code spends most of its time in the main loop in `oj_dump_cstr`. 
```
== Encoding mixed utf8 (5003001 bytes)
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [arm64-darwin24]
oj    12.000 i/100ms
oj    134.687 (± 2.2%) i/s    (7.42 ms/i) -    684.000 in …
```
> Optimize rails_xss_friendly_size and rails_friendly_size with ARM Neon instructions.

- ext/oj/dump.c
- ext/oj/simd.h
- test/test_long_strings.rb
This pull request optimizes `oj_dump_cstr` using ARM Neon instructions to locate characters that need to be escaped. It does so by implementing a state machine within the current structure of the code.
Note: It may be nice in the future to refactor this code into two distinct functions. One function for searching for characters that need to be escaped and another to do the escaping. 
Additionally, I hope this doesn't break any of the Unicode validation. If `do_unicode_validation == true` and this code detects a high byte, it forces all of the characters within that chunk of text through the current code. 
Both benchmarks compare `master` (commit: `4332ae9f81db7caed9411be445a145276c69d4fb`) vs this `arm-neon-optimize-oj-dump-cstr` branch (commit `5e8a65304633d87d0f13ce192ce3404de74bbb5b`) …
> ARM Neon optimization of `oj_dump_cstr`

- .github/workflows/clang-format.yml
- ext/oj/custom.c
- ext/oj/dump.c
- ext/oj/dump.h
- ext/oj/dump_compat.c
- ext/oj/dump_leaf.c
- ext/oj/dump_object.c
- ext/oj/dump_strict.c
- ext/oj/fast.c
- ext/oj/object.c
- ext/oj/oj.c
- ext/oj/rails.c
- ext/oj/wab.c
`size_t size = (int)RSTRING_LEN(string)` leads to out of bounds reads.
See https://github.com/samuel-williams-shopify/oj-overflow for more details.
> `size_t` everywhere.

- .github/workflows/CI.yml
- test/test_custom.rb
- test/test_strict.rb
- test/test_wab.rb
Wondering if it's OK to run tests on TruffleRuby now (it was disabled in 1025d247c57602742bbf268b45c9bb2fcddbda3e).
Now all tests pass on TruffleRuby (except tests that rely on `#fork`). See https://github.com/andrykonchin/oj/pull/1.
> Restore TruffleRuby in CI
