- .travis.yml
> Make Travis CI build faster

- README.md
Modify README section title to render properly.
> Render section title by bold font

- ext/oj/oj.c
- test/isolated/test_mimic_redefine.rb
- test/test_all.sh
I guess this should fix those:
https://github.com/ohler55/oj/issues/319
https://github.com/ruby-json-schema/json-schema/issues/366
> Do not redefine JSON::ParserError

- README.md
I omitted options that didn't appear to be tested.
> Add missing options in readme

- Rakefile
- oj.gemspec
- test/isolated_compatibility/data_compatibility_json.rb
- test/isolated_compatibility/data_compatibility_rails.rb
- test/isolated_compatibility/test_compatibility_json.rb
- test/isolated_compatibility/test_compatibility_rails.rb
Do you want me to leave only one commit in this PR? Can do that
> Compatibility tests

- test/isolated_compatibility/data_compatibility_json.rb
- test/isolated_compatibility/data_compatibility_rails.rb
Maybe will find more testcases. Scanning through rails tests
- [encoding_test.rb](https://github.com/rails/rails/blob/e8ba0c0f21e2660b90f872fa4595156ca6190c77/activesupport/test/json/encoding_test.rb)
- [encoding_test_cases.rb](https://github.com/rails/rails/blob/e8ba0c0f21e2660b90f872fa4595156ca6190c77/activesupport/test/json/encoding_test_cases.rb)
- [json_encoding_test.rb](https://github.com/ruby/ruby/blob/trunk/test/json/json_encoding_test.rb)
- [json_generator_test.rb](https://github.com/ruby/ruby/blob/trunk/test/json/json_generator_test.rb)
> More data for tests

- Rakefile
- test/activesupport4/Readme.md
- test/activesupport4/decoding_test.rb
- test/activesupport4/encoding_test.rb
- test/activesupport4/test_helper.rb
- test/activesupport5/Readme.md
- test/activesupport5/decoding_test.rb
- test/activesupport5/encoding_test.rb
- test/activesupport5/encoding_test_cases.rb
- test/activesupport5/test_helper.rb
- test/activesupport5/time_zone_test_helpers.rb
> ActiveSupport tests

- Rakefile
- appveyor.yml
> appveyor.yml

- README.md
> Remove call to suggest image from README

- lib/oj/error.rb
Single-line calls to create empty classes..
> Create empty classes with `Class.new`

- ext/oj/mimic_json.c
> Remove debugging output.

- ext/oj/mimic_json.c
> Add missing spaces in docs

- CHANGELOG.md
- ext/oj/parse.c
- ext/oj/sparse.c
> Fix comments to reflect JSON::ParserError instea of JSON::ParseError

- .travis.yml
- Rakefile
- gemfiles/rails_6.gemfile
- test/activesupport6/Readme.md
- test/activesupport6/abstract_unit.rb
- test/activesupport6/decoding_test.rb
- test/activesupport6/encoding_test.rb
- test/activesupport6/encoding_test_cases.rb
- test/activesupport6/test_common.rb
- test/activesupport6/test_helper.rb
- test/activesupport6/time_zone_test_helpers.rb
Same as #558, just with 6.0.0 test cases.
> Add Rails 6.0.0 test cases

- pages/Rails.md
- code updated to properly handle already encoded JSON strings
> Rails.md: Rails 3 encoder example update

- test/test_compat.rb
Fixes https://github.com/ohler55/oj/issues/635
> fix duplicate test names in test_compat.rb

- lib/oj/version.rb
Updating the version as a follow-up to yesterday's [PR](https://github.com/ohler55/oj/pull/644).
> Bump version

- ext/oj/dump.c
Related to https://github.com/ohler55/oj/pull/728
Previous PR, I had cleaned up at the end of creating it, but I forgot to edit a part.
Sorry.
> Fix string size calculation

- .github/workflows/CI.yml
Ref: https://github.com/actions/checkout
> Update GitHub checkout action to v3

- .github/workflows/CI.yml
- Rakefile
- test/json_gem/json_parser_test.rb
- test/test_custom.rb
- test/test_file.rb
- test/test_gc.rb
- test/test_integer_range.rb
- test/test_object.rb
- test/test_scp.rb
- test/test_strict.rb
- test/test_wab.rb
This PR will add TruffleRuby CI lane.
The failing tests are simply skipped now.
> Add TruffleRuby into CI

- ext/oj/fast.c
- ext/oj/intern.c
- ext/oj/saj2.c
- ext/oj/usual.c
- ext/oj/val_stack.c
Added some extra null checks for issues found when running very mark functions very aggressively while running OJ tests.
> Add some null checks to mark functions.

- ext/oj/oj.c
- pages/Options.md
> Add descriptions of the missing options to document

- .github/workflows/CI.yml
Ruby 3.2 has been released at Xmas :)
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
> Add Ruby 3.2 in CI

- .github/workflows/clang-format.yml
Copied over from earlier PR to `ox`
> Add CI job for clang-format

- .editorconfig
Copied over from the one created for `ox`
> Add EditorConfig for whitespace formats
